// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ApplyArtifactsRequestProtocol is request body for applying artifacts to a virtual machine.
public protocol ApplyArtifactsRequestProtocol : Codable {
     var artifacts: [ArtifactInstallPropertiesProtocol?]? { get set }
}
