// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ArmTemplateInfoProtocol is information about a generated ARM template.
public protocol ArmTemplateInfoProtocol : Codable {
     var template: [String: String?]? { get set }
     var parameters: [String: String?]? { get set }
}
