// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ArtifactParameterPropertiesProtocol is properties of an artifact parameter.
public protocol ArtifactParameterPropertiesProtocol : Codable {
     var name: String? { get set }
     var value: String? { get set }
}
