// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// CustomImagePropertiesProtocol is properties of a custom image.
public protocol CustomImagePropertiesProtocol : Codable {
     var vm: CustomImagePropertiesFromVmProtocol? { get set }
     var vhd: CustomImagePropertiesCustomProtocol? { get set }
     var description: String? { get set }
     var author: String? { get set }
     var creationDate: Date? { get set }
     var managedImageId: String? { get set }
     var provisioningState: String? { get set }
     var uniqueIdentifier: String? { get set }
}
