// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// DetachDataDiskPropertiesProtocol is request body for detaching data disk from a virtual machine.
public protocol DetachDataDiskPropertiesProtocol : Codable {
     var existingLabDiskId: String? { get set }
}
