// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// GenerateArmTemplateRequestProtocol is parameters for generating an ARM template for deploying artifacts.
public protocol GenerateArmTemplateRequestProtocol : Codable {
     var virtualMachineName: String? { get set }
     var parameters: [ParameterInfoProtocol?]? { get set }
     var location: String? { get set }
     var fileUploadOptions: FileUploadOptionsEnum? { get set }
}
