// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// LabPropertiesProtocol is properties of a lab.
public protocol LabPropertiesProtocol : Codable {
     var defaultStorageAccount: String? { get set }
     var defaultPremiumStorageAccount: String? { get set }
     var artifactsStorageAccount: String? { get set }
     var premiumDataDiskStorageAccount: String? { get set }
     var vaultName: String? { get set }
     var labStorageType: StorageTypeEnum? { get set }
     var createdDate: Date? { get set }
     var premiumDataDisks: PremiumDataDiskEnum? { get set }
     var provisioningState: String? { get set }
     var uniqueIdentifier: String? { get set }
}
