// ComputeNodeFillType enumerates the values for compute node fill type.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum ComputeNodeFillTypeEnum: String, Codable
{
// Pack specifies the pack state for compute node fill type.
    case Pack = "pack"
// Spread specifies the spread state for compute node fill type.
    case Spread = "spread"
}
