// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
import azureSwiftRuntime
internal struct JobScheduleStatisticsData : JobScheduleStatisticsProtocol {
    public var url: String
    public var startTime: Date
    public var lastUpdateTime: Date
    public var userCPUTime: String
    public var kernelCPUTime: String
    public var wallClockTime: String
    public var readIOps: Int64
    public var writeIOps: Int64
    public var readIOGiB: Double
    public var writeIOGiB: Double
    public var numSucceededTasks: Int64
    public var numFailedTasks: Int64
    public var numTaskRetries: Int64
    public var waitTime: String

        enum CodingKeys: String, CodingKey {case url = "url"
        case startTime = "startTime"
        case lastUpdateTime = "lastUpdateTime"
        case userCPUTime = "userCPUTime"
        case kernelCPUTime = "kernelCPUTime"
        case wallClockTime = "wallClockTime"
        case readIOps = "readIOps"
        case writeIOps = "writeIOps"
        case readIOGiB = "readIOGiB"
        case writeIOGiB = "writeIOGiB"
        case numSucceededTasks = "numSucceededTasks"
        case numFailedTasks = "numFailedTasks"
        case numTaskRetries = "numTaskRetries"
        case waitTime = "waitTime"
        }

  public init(url: String, startTime: Date, lastUpdateTime: Date, userCPUTime: String, kernelCPUTime: String, wallClockTime: String, readIOps: Int64, writeIOps: Int64, readIOGiB: Double, writeIOGiB: Double, numSucceededTasks: Int64, numFailedTasks: Int64, numTaskRetries: Int64, waitTime: String)  {
    self.url = url
    self.startTime = startTime
    self.lastUpdateTime = lastUpdateTime
    self.userCPUTime = userCPUTime
    self.kernelCPUTime = kernelCPUTime
    self.wallClockTime = wallClockTime
    self.readIOps = readIOps
    self.writeIOps = writeIOps
    self.readIOGiB = readIOGiB
    self.writeIOGiB = writeIOGiB
    self.numSucceededTasks = numSucceededTasks
    self.numFailedTasks = numFailedTasks
    self.numTaskRetries = numTaskRetries
    self.waitTime = waitTime
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
      self.url = try container.decode(String.self, forKey: .url)
        self.startTime = DateConverter.fromString(dateStr: (try container.decode(String?.self, forKey: .startTime)), format: .dateTime)!
        self.lastUpdateTime = DateConverter.fromString(dateStr: (try container.decode(String?.self, forKey: .lastUpdateTime)), format: .dateTime)!
    self.userCPUTime = try container.decode(String.self, forKey: .userCPUTime)
    self.kernelCPUTime = try container.decode(String.self, forKey: .kernelCPUTime)
    self.wallClockTime = try container.decode(String.self, forKey: .wallClockTime)
    self.readIOps = try container.decode(Int64.self, forKey: .readIOps)
    self.writeIOps = try container.decode(Int64.self, forKey: .writeIOps)
    self.readIOGiB = try container.decode(Double.self, forKey: .readIOGiB)
    self.writeIOGiB = try container.decode(Double.self, forKey: .writeIOGiB)
    self.numSucceededTasks = try container.decode(Int64.self, forKey: .numSucceededTasks)
    self.numFailedTasks = try container.decode(Int64.self, forKey: .numFailedTasks)
    self.numTaskRetries = try container.decode(Int64.self, forKey: .numTaskRetries)
    self.waitTime = try container.decode(String.self, forKey: .waitTime)
    if var pageDecoder = decoder as? PageDecoder  {
      if pageDecoder.isPagedData,
        let nextLinkName = pageDecoder.nextLinkName {
          pageDecoder.nextLink = try UnknownCodingKey.decodeStringForKey(decoder: decoder, keyForDecode: nextLinkName)
      }
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.url, forKey: .url)
    try container.encode(DateConverter.toString(date: self.startTime, format: .dateTime), forKey: .startTime)
    try container.encode(DateConverter.toString(date: self.lastUpdateTime, format: .dateTime), forKey: .lastUpdateTime)
    try container.encode(self.userCPUTime, forKey: .userCPUTime)
    try container.encode(self.kernelCPUTime, forKey: .kernelCPUTime)
    try container.encode(self.wallClockTime, forKey: .wallClockTime)
    try container.encode(self.readIOps, forKey: .readIOps)
    try container.encode(self.writeIOps, forKey: .writeIOps)
    try container.encode(self.readIOGiB, forKey: .readIOGiB)
    try container.encode(self.writeIOGiB, forKey: .writeIOGiB)
    try container.encode(self.numSucceededTasks, forKey: .numSucceededTasks)
    try container.encode(self.numFailedTasks, forKey: .numFailedTasks)
    try container.encode(self.numTaskRetries, forKey: .numTaskRetries)
    try container.encode(self.waitTime, forKey: .waitTime)
  }
}

extension DataFactory {
  public static func createJobScheduleStatisticsProtocol(url: String, startTime: Date, lastUpdateTime: Date, userCPUTime: String, kernelCPUTime: String, wallClockTime: String, readIOps: Int64, writeIOps: Int64, readIOGiB: Double, writeIOGiB: Double, numSucceededTasks: Int64, numFailedTasks: Int64, numTaskRetries: Int64, waitTime: String) -> JobScheduleStatisticsProtocol {
    return JobScheduleStatisticsData(url: url, startTime: startTime, lastUpdateTime: lastUpdateTime, userCPUTime: userCPUTime, kernelCPUTime: kernelCPUTime, wallClockTime: wallClockTime, readIOps: readIOps, writeIOps: writeIOps, readIOGiB: readIOGiB, writeIOGiB: writeIOGiB, numSucceededTasks: numSucceededTasks, numFailedTasks: numFailedTasks, numTaskRetries: numTaskRetries, waitTime: waitTime)
  }
}
