// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
import azureSwiftRuntime
internal struct OSDiskData : OSDiskProtocol {
    public var caching: CachingTypeEnum?

        enum CodingKeys: String, CodingKey {case caching = "caching"
        }

  public init()  {
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
      if container.contains(.caching) {
        self.caching = try container.decode(CachingTypeEnum?.self, forKey: .caching)
    }
    if var pageDecoder = decoder as? PageDecoder  {
      if pageDecoder.isPagedData,
        let nextLinkName = pageDecoder.nextLinkName {
          pageDecoder.nextLink = try UnknownCodingKey.decodeStringForKey(decoder: decoder, keyForDecode: nextLinkName)
      }
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    if self.caching != nil {try container.encode(self.caching, forKey: .caching)}
  }
}

extension DataFactory {
  public static func createOSDiskProtocol() -> OSDiskProtocol {
    return OSDiskData()
  }
}
