// PoolLifetimeOption enumerates the values for pool lifetime option.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum PoolLifetimeOptionEnum: String, Codable
{
// PoolLifetimeOptionJob specifies the pool lifetime option job state for pool lifetime option.
    case PoolLifetimeOptionJob = "job"
// PoolLifetimeOptionJobSchedule specifies the pool lifetime option job schedule state for pool lifetime option.
    case PoolLifetimeOptionJobSchedule = "jobschedule"
}
