// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ComputePolicyProtocol is data Lake Analytics compute policy information.
public protocol ComputePolicyProtocol : SubResourceProtocol {
     var properties: ComputePolicyPropertiesProtocol? { get set }
}
