// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// StorageAccountInformationProtocol is azure Storage account information.
public protocol StorageAccountInformationProtocol : SubResourceProtocol {
     var properties: StorageAccountInformationPropertiesProtocol? { get set }
}
