// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// DiskPropertiesProtocol is disk resource properties.
public protocol DiskPropertiesProtocol : Codable {
     var timeCreated: Date? { get set }
     var osType: OperatingSystemTypesEnum? { get set }
     var creationData: CreationDataProtocol { get set }
     var diskSizeGB: Int32? { get set }
     var encryptionSettings: EncryptionSettingsProtocol? { get set }
     var provisioningState: String? { get set }
}
