// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// SshPublicKeyProtocol is contains information about SSH certificate public key and the path on the Linux VM where the
// public key is placed.
public protocol SshPublicKeyProtocol : Codable {
     var path: String? { get set }
     var keyData: String? { get set }
}
