// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// VirtualMachineScaleSetSkuCapacityProtocol is describes scaling information of a sku.
public protocol VirtualMachineScaleSetSkuCapacityProtocol : Codable {
     var minimum: Int64? { get set }
     var maximum: Int64? { get set }
     var defaultCapacity: Int64? { get set }
     var scaleType: VirtualMachineScaleSetSkuScaleTypeEnum? { get set }
}
