// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// VirtualMachineExtensionInstanceViewProtocol is the instance view of a virtual machine extension.
public protocol VirtualMachineExtensionInstanceViewProtocol : Codable {
     var name: String? { get set }
     var type: String? { get set }
     var typeHandlerVersion: String? { get set }
     var substatuses: [InstanceViewStatusProtocol?]? { get set }
     var statuses: [InstanceViewStatusProtocol?]? { get set }
}
