// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
import azureSwiftRuntime
internal struct DetachDataDiskPropertiesData : DetachDataDiskPropertiesProtocol {
    public var existingLabDiskId: String?

        enum CodingKeys: String, CodingKey {case existingLabDiskId = "existingLabDiskId"
        }

  public init()  {
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
      if container.contains(.existingLabDiskId) {
        self.existingLabDiskId = try container.decode(String?.self, forKey: .existingLabDiskId)
    }
    if var pageDecoder = decoder as? PageDecoder  {
      if pageDecoder.isPagedData,
        let nextLinkName = pageDecoder.nextLinkName {
          pageDecoder.nextLink = try UnknownCodingKey.decodeStringForKey(decoder: decoder, keyForDecode: nextLinkName)
      }
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    if self.existingLabDiskId != nil {try container.encode(self.existingLabDiskId, forKey: .existingLabDiskId)}
  }
}

extension DataFactory {
  public static func createDetachDataDiskPropertiesProtocol() -> DetachDataDiskPropertiesProtocol {
    return DetachDataDiskPropertiesData()
  }
}
