// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

// WorkflowVersions is the REST API for Azure Logic Apps.
import Foundation
import azureSwiftRuntime
extension Commands {
public struct WorkflowVersions {
    public static func Get(subscriptionId: String, resourceGroupName: String, workflowName: String, versionId: String) -> WorkflowVersionsGet {
        return GetCommand(subscriptionId: subscriptionId, resourceGroupName: resourceGroupName, workflowName: workflowName, versionId: versionId)
    }
    public static func List(subscriptionId: String, resourceGroupName: String, workflowName: String) -> WorkflowVersionsList {
        return ListCommand(subscriptionId: subscriptionId, resourceGroupName: resourceGroupName, workflowName: workflowName)
    }
    public static func ListCallbackUrl(subscriptionId: String, resourceGroupName: String, workflowName: String, versionId: String, triggerName: String) -> WorkflowVersionsListCallbackUrl {
        return ListCallbackUrlCommand(subscriptionId: subscriptionId, resourceGroupName: resourceGroupName, workflowName: workflowName, versionId: versionId, triggerName: triggerName)
    }
}
}
