// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

// WorkflowRunActions is the REST API for Azure Logic Apps.
import Foundation
import azureSwiftRuntime
extension Commands {
public struct WorkflowRunActions {
    public static func Get(subscriptionId: String, resourceGroupName: String, workflowName: String, runName: String, actionName: String) -> WorkflowRunActionsGet {
        return GetCommand(subscriptionId: subscriptionId, resourceGroupName: resourceGroupName, workflowName: workflowName, runName: runName, actionName: actionName)
    }
    public static func List(subscriptionId: String, resourceGroupName: String, workflowName: String, runName: String) -> WorkflowRunActionsList {
        return ListCommand(subscriptionId: subscriptionId, resourceGroupName: resourceGroupName, workflowName: workflowName, runName: runName)
    }
}
}
