// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

// Images is the compute Client
import Foundation
import azureSwiftRuntime
extension Commands {
public struct Images {
    public static func CreateOrUpdate(resourceGroupName: String, imageName: String, subscriptionId: String, parameters: ImageProtocol) -> ImagesCreateOrUpdate {
        return CreateOrUpdateCommand(resourceGroupName: resourceGroupName, imageName: imageName, subscriptionId: subscriptionId, parameters: parameters)
    }
    public static func Delete(resourceGroupName: String, imageName: String, subscriptionId: String) -> ImagesDelete {
        return DeleteCommand(resourceGroupName: resourceGroupName, imageName: imageName, subscriptionId: subscriptionId)
    }
    public static func Get(resourceGroupName: String, imageName: String, subscriptionId: String) -> ImagesGet {
        return GetCommand(resourceGroupName: resourceGroupName, imageName: imageName, subscriptionId: subscriptionId)
    }
    public static func List(subscriptionId: String) -> ImagesList {
        return ListCommand(subscriptionId: subscriptionId)
    }
    public static func ListByResourceGroup(resourceGroupName: String, subscriptionId: String) -> ImagesListByResourceGroup {
        return ListByResourceGroupCommand(resourceGroupName: resourceGroupName, subscriptionId: subscriptionId)
    }
}
}
