// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// CertificateListResultProtocol is the response model for the list certificate operation.
public protocol CertificateListResultProtocol : Codable {
     var value: [CertificateProtocol?]? { get set }
     var _nextLink: String? { get set }
}
