// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ConnectionUpdateParametersProtocol is the parameters supplied to the update connection operation.
public protocol ConnectionUpdateParametersProtocol : Codable {
     var name: String? { get set }
     var properties: ConnectionUpdatePropertiesProtocol? { get set }
}
