// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ConnectionCreateOrUpdatePropertiesProtocol is the properties of the create connection properties
public protocol ConnectionCreateOrUpdatePropertiesProtocol : Codable {
     var description: String? { get set }
     var connectionType: ConnectionTypeAssociationPropertyProtocol { get set }
     var fieldDefinitionValues: [String:String]? { get set }
}
