// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ScheduleUpdatePropertiesProtocol is the parameters supplied to the update schedule operation.
public protocol ScheduleUpdatePropertiesProtocol : Codable {
     var description: String? { get set }
     var isEnabled: Bool? { get set }
}
