// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// SourceControlSyncJobListResultProtocol is the response model for the list source control sync jobs operation.
public protocol SourceControlSyncJobListResultProtocol : Codable {
     var value: [SourceControlSyncJobProtocol?]? { get set }
     var _nextLink: String? { get set }
}
