// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// VariablePropertiesProtocol is definition of the varible properties
public protocol VariablePropertiesProtocol : Codable {
     var value: String? { get set }
     var isEncrypted: Bool? { get set }
     var creationTime: Date? { get set }
     var lastModifiedTime: Date? { get set }
     var description: String? { get set }
}
