// MonitorProtocol enumerates the values for monitor protocol.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum MonitorProtocolEnum: String, Codable
{
// HTTP specifies the http state for monitor protocol.
    case HTTP = "HTTP"
// HTTPS specifies the https state for monitor protocol.
    case HTTPS = "HTTPS"
// TCP specifies the tcp state for monitor protocol.
    case TCP = "TCP"
}
