// ProfileMonitorStatus enumerates the values for profile monitor status.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum ProfileMonitorStatusEnum: String, Codable
{
// ProfileMonitorStatusCheckingEndpoints specifies the profile monitor status checking endpoints state for profile
// monitor status.
    case ProfileMonitorStatusCheckingEndpoints = "CheckingEndpoints"
// ProfileMonitorStatusDegraded specifies the profile monitor status degraded state for profile monitor status.
    case ProfileMonitorStatusDegraded = "Degraded"
// ProfileMonitorStatusDisabled specifies the profile monitor status disabled state for profile monitor status.
    case ProfileMonitorStatusDisabled = "Disabled"
// ProfileMonitorStatusInactive specifies the profile monitor status inactive state for profile monitor status.
    case ProfileMonitorStatusInactive = "Inactive"
// ProfileMonitorStatusOnline specifies the profile monitor status online state for profile monitor status.
    case ProfileMonitorStatusOnline = "Online"
}
