// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// KeyVaultPropertiesProtocol is properties of key vault.
public protocol KeyVaultPropertiesProtocol : Codable {
     var keyName: String? { get set }
     var keyVersion: String? { get set }
     var keyVaultUri: String? { get set }
}
