// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
import Foundation
// StorageAccountPropertiesProtocol is properties of the storage account.
public protocol StorageAccountPropertiesProtocol : Codable {
     var provisioningState: ProvisioningState? { get set }
     var primaryEndpoints: EndpointsProtocol? { get set }
     var primaryLocation: String? { get set }
     var statusOfPrimary: AccountStatus? { get set }
     var lastGeoFailoverTime: Date? { get set }
     var secondaryLocation: String? { get set }
     var statusOfSecondary: AccountStatus? { get set }
     var creationTime: Date? { get set }
     var customDomain: CustomDomainProtocol? { get set }
     var secondaryEndpoints: EndpointsProtocol? { get set }
     var encryption: EncryptionProtocol? { get set }
     var accessTier: AccessTier? { get set }
     var enableHttpsTrafficOnly: Bool? { get set }
     var networkRuleSet: NetworkRuleSetProtocol? { get set }
}
