// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// StorageAccountKeyProtocol is an access key for the storage account.
public protocol StorageAccountKeyProtocol : Codable {
     var keyName: String? { get set }
     var value: String? { get set }
     var permissions: KeyPermissionEnum? { get set }
}
