// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
import Foundation
// UsageNameProtocol is the usage names that can be used; currently limited to StorageAccount.
public protocol UsageNameProtocol : Codable {
     var value: String? { get set }
     var localizedValue: String? { get set }
}
