// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
import azureSwiftRuntime
internal struct ContainerServiceMasterProfileData : ContainerServiceMasterProfileProtocol {
    public var count: Int32?
    public var dnsPrefix: String
    public var fqdn: String?

        enum CodingKeys: String, CodingKey {case count = "count"
        case dnsPrefix = "dnsPrefix"
        case fqdn = "fqdn"
        }

  public init(dnsPrefix: String)  {
    self.dnsPrefix = dnsPrefix
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
      if container.contains(.count) {
        self.count = try container.decode(Int32?.self, forKey: .count)
    }
    self.dnsPrefix = try container.decode(String.self, forKey: .dnsPrefix)
    if container.contains(.fqdn) {
        self.fqdn = try container.decode(String?.self, forKey: .fqdn)
    }
    if var pageDecoder = decoder as? PageDecoder  {
      if pageDecoder.isPagedData,
        let nextLinkName = pageDecoder.nextLinkName {
          pageDecoder.nextLink = try UnknownCodingKey.decodeStringForKey(decoder: decoder, keyForDecode: nextLinkName)
      }
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    if self.count != nil {try container.encode(self.count, forKey: .count)}
    try container.encode(self.dnsPrefix, forKey: .dnsPrefix)
    if self.fqdn != nil {try container.encode(self.fqdn, forKey: .fqdn)}
  }
}

extension DataFactory {
  public static func createContainerServiceMasterProfileProtocol(dnsPrefix: String) -> ContainerServiceMasterProfileProtocol {
    return ContainerServiceMasterProfileData(dnsPrefix: dnsPrefix)
  }
}
