// IPVersion enumerates the values for ip version.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum IPVersionEnum: String, Codable
{
// IPv4 specifies the i pv 4 state for ip version.
    case IPv4 = "IPv4"
// IPv6 specifies the i pv 6 state for ip version.
    case IPv6 = "IPv6"
}
