// ResourceSkuRestrictionsType enumerates the values for resource sku restrictions type.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum ResourceSkuRestrictionsTypeEnum: String, Codable
{
// Location specifies the location state for resource sku restrictions type.
    case Location = "Location"
// Zone specifies the zone state for resource sku restrictions type.
    case Zone = "Zone"
}
