// ComputeModeOptions enumerates the values for compute mode options.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum ComputeModeOptionsEnum: String, Codable
{
// ComputeModeOptionsDedicated specifies the compute mode options dedicated state for compute mode options.
    case ComputeModeOptionsDedicated = "Dedicated"
// ComputeModeOptionsDynamic specifies the compute mode options dynamic state for compute mode options.
    case ComputeModeOptionsDynamic = "Dynamic"
// ComputeModeOptionsShared specifies the compute mode options shared state for compute mode options.
    case ComputeModeOptionsShared = "Shared"
}
