// CustomHostNameDnsRecordType enumerates the values for custom host name dns record type.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum CustomHostNameDnsRecordTypeEnum: String, Codable
{
// A specifies the a state for custom host name dns record type.
    case A = "A"
// CName specifies the c name state for custom host name dns record type.
    case CName = "CName"
}
