// RouteType enumerates the values for route type.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum RouteTypeEnum: String, Codable
{
// DEFAULT specifies the default state for route type.
    case DEFAULT = "DEFAULT"
// INHERITED specifies the inherited state for route type.
    case INHERITED = "INHERITED"
// STATIC specifies the static state for route type.
    case STATIC = "STATIC"
}
