// SiteLoadBalancing enumerates the values for site load balancing.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum SiteLoadBalancingEnum: String, Codable
{
// LeastRequests specifies the least requests state for site load balancing.
    case LeastRequests = "LeastRequests"
// LeastResponseTime specifies the least response time state for site load balancing.
    case LeastResponseTime = "LeastResponseTime"
// RequestHash specifies the request hash state for site load balancing.
    case RequestHash = "RequestHash"
// WeightedRoundRobin specifies the weighted round robin state for site load balancing.
    case WeightedRoundRobin = "WeightedRoundRobin"
// WeightedTotalTraffic specifies the weighted total traffic state for site load balancing.
    case WeightedTotalTraffic = "WeightedTotalTraffic"
}
