// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
import azureSwiftRuntime
internal struct VnetGatewayPropertiesData : VnetGatewayPropertiesProtocol {
    public var vnetName: String?
    public var vpnPackageUri: String?

        enum CodingKeys: String, CodingKey {case vnetName = "vnetName"
        case vpnPackageUri = "vpnPackageUri"
        }

  public init()  {
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
      if container.contains(.vnetName) {
        self.vnetName = try container.decode(String?.self, forKey: .vnetName)
    }
    if container.contains(.vpnPackageUri) {
        self.vpnPackageUri = try container.decode(String?.self, forKey: .vpnPackageUri)
    }
    if var pageDecoder = decoder as? PageDecoder  {
      if pageDecoder.isPagedData,
        let nextLinkName = pageDecoder.nextLinkName {
          pageDecoder.nextLink = try UnknownCodingKey.decodeStringForKey(decoder: decoder, keyForDecode: nextLinkName)
      }
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    if self.vnetName != nil {try container.encode(self.vnetName, forKey: .vnetName)}
    if self.vpnPackageUri != nil {try container.encode(self.vpnPackageUri, forKey: .vpnPackageUri)}
  }
}

extension DataFactory {
  public static func createVnetGatewayPropertiesProtocol() -> VnetGatewayPropertiesProtocol {
    return VnetGatewayPropertiesData()
  }
}
