// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// UsageDetailPropertiesProtocol is the properties of the usage detail.
public protocol UsageDetailPropertiesProtocol : Codable {
     var billingPeriodId: String? { get set }
     var invoiceId: String? { get set }
     var usageStart: Date? { get set }
     var usageEnd: Date? { get set }
     var instanceName: String? { get set }
     var instanceId: String? { get set }
     var instanceLocation: String? { get set }
     var currency: String? { get set }
     var usageQuantity: Decimal? { get set }
     var billableQuantity: Decimal? { get set }
     var pretaxCost: Decimal? { get set }
     var isEstimated: Bool? { get set }
     var meterId: String? { get set }
     var meterDetails: MeterDetailsProtocol? { get set }
     var subscriptionGuid: String? { get set }
     var subscriptionName: String? { get set }
     var accountName: String? { get set }
     var departmentName: String? { get set }
     var product: String? { get set }
     var consumedService: String? { get set }
     var costCenter: String? { get set }
     var additionalProperties: String? { get set }
}
