// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// VaultAccessPolicyParametersProtocol is parameters for updating the access policy in a vault
public protocol VaultAccessPolicyParametersProtocol : Codable {
     var id: String? { get set }
     var name: String? { get set }
     var type: String? { get set }
     var location: String? { get set }
     var properties: VaultAccessPolicyPropertiesProtocol { get set }
}
