// Access enumerates the values for access.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum AccessEnum: String, Codable
{
// Allow specifies the allow state for access.
    case Allow = "Allow"
// Deny specifies the deny state for access.
    case Deny = "Deny"
}
