// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
import azureSwiftRuntime
internal struct IpTagData : IpTagProtocol {
    public var ipTagType: String?
    public var tag: String?

        enum CodingKeys: String, CodingKey {case ipTagType = "ipTagType"
        case tag = "tag"
        }

  public init()  {
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
      if container.contains(.ipTagType) {
        self.ipTagType = try container.decode(String?.self, forKey: .ipTagType)
    }
    if container.contains(.tag) {
        self.tag = try container.decode(String?.self, forKey: .tag)
    }
    if var pageDecoder = decoder as? PageDecoder  {
      if pageDecoder.isPagedData,
        let nextLinkName = pageDecoder.nextLinkName {
          pageDecoder.nextLink = try UnknownCodingKey.decodeStringForKey(decoder: decoder, keyForDecode: nextLinkName)
      }
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    if self.ipTagType != nil {try container.encode(self.ipTagType, forKey: .ipTagType)}
    if self.tag != nil {try container.encode(self.tag, forKey: .tag)}
  }
}

extension DataFactory {
  public static func createIpTagProtocol() -> IpTagProtocol {
    return IpTagData()
  }
}
