// PfsGroup enumerates the values for pfs group.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum PfsGroupEnum: String, Codable
{
// PfsGroupECP256 specifies the pfs group ecp256 state for pfs group.
    case PfsGroupECP256 = "ECP256"
// PfsGroupECP384 specifies the pfs group ecp384 state for pfs group.
    case PfsGroupECP384 = "ECP384"
// PfsGroupNone specifies the pfs group none state for pfs group.
    case PfsGroupNone = "None"
// PfsGroupPFS1 specifies the pfs group pfs1 state for pfs group.
    case PfsGroupPFS1 = "PFS1"
// PfsGroupPFS2 specifies the pfs group pfs2 state for pfs group.
    case PfsGroupPFS2 = "PFS2"
// PfsGroupPFS2048 specifies the pfs group pfs2048 state for pfs group.
    case PfsGroupPFS2048 = "PFS2048"
// PfsGroupPFS24 specifies the pfs group pfs24 state for pfs group.
    case PfsGroupPFS24 = "PFS24"
}
