// PublicIPAddressSkuName enumerates the values for public ip address sku name.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum PublicIPAddressSkuNameEnum: String, Codable
{
// PublicIPAddressSkuNameBasic specifies the public ip address sku name basic state for public ip address sku name.
    case PublicIPAddressSkuNameBasic = "Basic"
// PublicIPAddressSkuNameStandard specifies the public ip address sku name standard state for public ip address sku
// name.
    case PublicIPAddressSkuNameStandard = "Standard"
}
