// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
import azureSwiftRuntime
internal struct RoutePropertiesFormatData : RoutePropertiesFormatProtocol {
    public var addressPrefix: String?
    public var nextHopType: RouteNextHopTypeEnum
    public var nextHopIpAddress: String?
    public var provisioningState: String?

        enum CodingKeys: String, CodingKey {case addressPrefix = "addressPrefix"
        case nextHopType = "nextHopType"
        case nextHopIpAddress = "nextHopIpAddress"
        case provisioningState = "provisioningState"
        }

  public init(nextHopType: RouteNextHopTypeEnum)  {
    self.nextHopType = nextHopType
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
      if container.contains(.addressPrefix) {
        self.addressPrefix = try container.decode(String?.self, forKey: .addressPrefix)
    }
    self.nextHopType = try container.decode(RouteNextHopTypeEnum.self, forKey: .nextHopType)
    if container.contains(.nextHopIpAddress) {
        self.nextHopIpAddress = try container.decode(String?.self, forKey: .nextHopIpAddress)
    }
    if container.contains(.provisioningState) {
        self.provisioningState = try container.decode(String?.self, forKey: .provisioningState)
    }
    if var pageDecoder = decoder as? PageDecoder  {
      if pageDecoder.isPagedData,
        let nextLinkName = pageDecoder.nextLinkName {
          pageDecoder.nextLink = try UnknownCodingKey.decodeStringForKey(decoder: decoder, keyForDecode: nextLinkName)
      }
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    if self.addressPrefix != nil {try container.encode(self.addressPrefix, forKey: .addressPrefix)}
    try container.encode(self.nextHopType, forKey: .nextHopType)
    if self.nextHopIpAddress != nil {try container.encode(self.nextHopIpAddress, forKey: .nextHopIpAddress)}
    if self.provisioningState != nil {try container.encode(self.provisioningState, forKey: .provisioningState)}
  }
}

extension DataFactory {
  public static func createRoutePropertiesFormatProtocol(nextHopType: RouteNextHopTypeEnum) -> RoutePropertiesFormatProtocol {
    return RoutePropertiesFormatData(nextHopType: nextHopType)
  }
}
