// ServiceProviderProvisioningState enumerates the values for service provider provisioning state.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum ServiceProviderProvisioningStateEnum: String, Codable
{
// Deprovisioning specifies the deprovisioning state for service provider provisioning state.
    case Deprovisioning = "Deprovisioning"
// NotProvisioned specifies the not provisioned state for service provider provisioning state.
    case NotProvisioned = "NotProvisioned"
// Provisioned specifies the provisioned state for service provider provisioning state.
    case Provisioned = "Provisioned"
// Provisioning specifies the provisioning state for service provider provisioning state.
    case Provisioning = "Provisioning"
}
