// DaysOfWeek enumerates the values for days of week.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum DaysOfWeekEnum: String, Codable
{
// DaysOfWeekFriday specifies the days of week friday state for days of week.
    case DaysOfWeekFriday = "Friday"
// DaysOfWeekMonday specifies the days of week monday state for days of week.
    case DaysOfWeekMonday = "Monday"
// DaysOfWeekSaturday specifies the days of week saturday state for days of week.
    case DaysOfWeekSaturday = "Saturday"
// DaysOfWeekSunday specifies the days of week sunday state for days of week.
    case DaysOfWeekSunday = "Sunday"
// DaysOfWeekThursday specifies the days of week thursday state for days of week.
    case DaysOfWeekThursday = "Thursday"
// DaysOfWeekTuesday specifies the days of week tuesday state for days of week.
    case DaysOfWeekTuesday = "Tuesday"
// DaysOfWeekWednesday specifies the days of week wednesday state for days of week.
    case DaysOfWeekWednesday = "Wednesday"
}
