// EncryptionAlgorithm enumerates the values for encryption algorithm.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum EncryptionAlgorithmEnum: String, Codable
{
// EncryptionAlgorithmAES128 specifies the encryption algorithm aes128 state for encryption algorithm.
    case EncryptionAlgorithmAES128 = "AES128"
// EncryptionAlgorithmAES192 specifies the encryption algorithm aes192 state for encryption algorithm.
    case EncryptionAlgorithmAES192 = "AES192"
// EncryptionAlgorithmAES256 specifies the encryption algorithm aes256 state for encryption algorithm.
    case EncryptionAlgorithmAES256 = "AES256"
// EncryptionAlgorithmDES3 specifies the encryption algorithm des3 state for encryption algorithm.
    case EncryptionAlgorithmDES3 = "DES3"
// EncryptionAlgorithmNone specifies the encryption algorithm none state for encryption algorithm.
    case EncryptionAlgorithmNone = "None"
// EncryptionAlgorithmNotSpecified specifies the encryption algorithm not specified state for encryption algorithm.
    case EncryptionAlgorithmNotSpecified = "NotSpecified"
// EncryptionAlgorithmRC2 specifies the encryption algorithm rc2 state for encryption algorithm.
    case EncryptionAlgorithmRC2 = "RC2"
}
