// X12TimeFormat enumerates the values for x12 time format.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum X12TimeFormatEnum: String, Codable
{
// X12TimeFormatHHMM specifies the x12 time format hhmm state for x12 time format.
    case X12TimeFormatHHMM = "HHMM"
// X12TimeFormatHHMMSS specifies the x12 time format hhmmss state for x12 time format.
    case X12TimeFormatHHMMSS = "HHMMSS"
// X12TimeFormatHHMMSSd specifies the x12 time format hhmms sd state for x12 time format.
    case X12TimeFormatHHMMSSd = "HHMMSSd"
// X12TimeFormatHHMMSSdd specifies the x12 time format hhmms sdd state for x12 time format.
    case X12TimeFormatHHMMSSdd = "HHMMSSdd"
// X12TimeFormatNotSpecified specifies the x12 time format not specified state for x12 time format.
    case X12TimeFormatNotSpecified = "NotSpecified"
}
