// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// CognitiveServicesAccountCreateParametersProtocol is the parameters to provide for the account.
public protocol CognitiveServicesAccountCreateParametersProtocol : Codable {
     var sku: SkuProtocol { get set }
     var kind: KindEnum { get set }
     var location: String { get set }
     var tags: [String:String]? { get set }
     var properties: [String: String?] { get set }
}
