// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ApplicationGatewaySslPredefinedPolicyPropertiesFormatProtocol is properties of ApplicationGatewaySslPredefinedPolicy
public protocol ApplicationGatewaySslPredefinedPolicyPropertiesFormatProtocol : Codable {
     var cipherSuites: [ApplicationGatewaySslCipherSuiteEnum?]? { get set }
     var minProtocolVersion: ApplicationGatewaySslProtocolEnum? { get set }
}
