// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ApplicationGatewayRequestRoutingRuleProtocol is request routing rule of an application gateway.
public protocol ApplicationGatewayRequestRoutingRuleProtocol : SubResourceProtocol {
     var properties: ApplicationGatewayRequestRoutingRulePropertiesFormatProtocol? { get set }
     var name: String? { get set }
     var etag: String? { get set }
     var type: String? { get set }
}
