// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ApplicationGatewayListResultProtocol is response for ListApplicationGateways API service call.
public protocol ApplicationGatewayListResultProtocol : Codable {
     var value: [ApplicationGatewayProtocol?]? { get set }
     var _nextLink: String? { get set }
}
