// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ApplicationGatewayFrontendIPConfigurationPropertiesFormatProtocol is properties of Frontend IP configuration of an
// application gateway.
public protocol ApplicationGatewayFrontendIPConfigurationPropertiesFormatProtocol : Codable {
     var privateIPAddress: String? { get set }
     var privateIPAllocationMethod: IPAllocationMethodEnum? { get set }
     var subnet: SubResourceProtocol? { get set }
     var publicIPAddress: SubResourceProtocol? { get set }
     var provisioningState: String? { get set }
}
