// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ConnectionMonitorParametersProtocol is parameters that define the operation to create a connection monitor.
public protocol ConnectionMonitorParametersProtocol : Codable {
     var source: ConnectionMonitorSourceProtocol { get set }
     var destination: ConnectionMonitorDestinationProtocol { get set }
     var autoStart: Bool? { get set }
     var monitoringIntervalInSeconds: Int32? { get set }
}
