// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ConnectionStateSnapshotProtocol is connection state snapshot.
public protocol ConnectionStateSnapshotProtocol : Codable {
     var connectionState: ConnectionStateEnum? { get set }
     var startTime: Date? { get set }
     var endTime: Date? { get set }
     var evaluationState: EvaluationStateEnum? { get set }
     var hops: [ConnectivityHopProtocol?]? { get set }
}
