// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ExpressRouteCircuitArpTableProtocol is the ARP table associated with the ExpressRouteCircuit.
public protocol ExpressRouteCircuitArpTableProtocol : Codable {
     var age: Int32? { get set }
     var interface: String? { get set }
     var ipAddress: String? { get set }
     var macAddress: String? { get set }
}
