// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ExpressRouteCircuitPeeringListResultProtocol is response for ListPeering API service call retrieves all peerings
// that belong to an ExpressRouteCircuit.
public protocol ExpressRouteCircuitPeeringListResultProtocol : Codable {
     var value: [ExpressRouteCircuitPeeringProtocol?]? { get set }
     var _nextLink: String? { get set }
}
