// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// FlowLogStatusParametersProtocol is parameters that define a resource to query flow log status.
public protocol FlowLogStatusParametersProtocol : Codable {
     var targetResourceId: String { get set }
}
