// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// GatewayRouteListResultProtocol is list of virtual network gateway routes
public protocol GatewayRouteListResultProtocol : Codable {
     var value: [GatewayRouteProtocol?]? { get set }
}
