// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// Ipv6ExpressRouteCircuitPeeringConfigProtocol is contains IPv6 peering config.
public protocol Ipv6ExpressRouteCircuitPeeringConfigProtocol : Codable {
     var primaryPeerAddressPrefix: String? { get set }
     var secondaryPeerAddressPrefix: String? { get set }
     var microsoftPeeringConfig: ExpressRouteCircuitPeeringConfigProtocol? { get set }
     var routeFilter: RouteFilterProtocol? { get set }
     var state: ExpressRouteCircuitPeeringStateEnum? { get set }
}
