// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// LoadBalancerFrontendIPConfigurationListResultProtocol is response for ListFrontendIPConfiguration API service call.
public protocol LoadBalancerFrontendIPConfigurationListResultProtocol : Codable {
     var value: [FrontendIPConfigurationProtocol?]? { get set }
     var _nextLink: String? { get set }
}
