// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// NetworkWatcherListResultProtocol is list of network watcher resources.
public protocol NetworkWatcherListResultProtocol : Codable {
     var value: [NetworkWatcherProtocol?]? { get set }
}
