// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// SecurityGroupNetworkInterfaceProtocol is network interface and all its associated security rules.
public protocol SecurityGroupNetworkInterfaceProtocol : Codable {
     var id: String? { get set }
     var securityRuleAssociations: SecurityRuleAssociationsProtocol? { get set }
}
