// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// VpnClientConfigurationProtocol is vpnClientConfiguration for P2S client.
public protocol VpnClientConfigurationProtocol : Codable {
     var vpnClientAddressPool: AddressSpaceProtocol? { get set }
     var vpnClientRootCertificates: [VpnClientRootCertificateProtocol?]? { get set }
     var vpnClientRevokedCertificates: [VpnClientRevokedCertificateProtocol?]? { get set }
     var vpnClientProtocols: [VpnClientProtocolEnum?]? { get set }
     var radiusServerAddress: String? { get set }
     var radiusServerSecret: String? { get set }
}
