// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// PowerShellSessionResourceProtocol is a PowerShell session resource (practically equivalent to a runspace instance).
public protocol PowerShellSessionResourceProtocol : ResourceProtocol {
     var properties: PowerShellSessionResourcePropertiesProtocol? { get set }
}
