// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// VersionProtocol is a multipart-numeric version number.
public protocol VersionProtocol : Codable {
     var major: Int32? { get set }
     var minor: Int32? { get set }
     var build: Int32? { get set }
     var revision: Int32? { get set }
     var majorRevision: Int32? { get set }
     var minorRevision: Int32? { get set }
}
