// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
import azureSwiftRuntime
internal struct ServiceBusTopicOutputDataSourcePropertiesData : ServiceBusTopicOutputDataSourcePropertiesProtocol, ServiceBusDataSourcePropertiesProtocol {
    public var serviceBusNamespace: String?
    public var sharedAccessPolicyName: String?
    public var sharedAccessPolicyKey: String?
    public var topicName: String?
    public var propertyColumns: [String]?

        enum CodingKeys: String, CodingKey {case serviceBusNamespace = "serviceBusNamespace"
        case sharedAccessPolicyName = "sharedAccessPolicyName"
        case sharedAccessPolicyKey = "sharedAccessPolicyKey"
        case topicName = "topicName"
        case propertyColumns = "propertyColumns"
        }

  public init()  {
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
      if container.contains(.serviceBusNamespace) {
        self.serviceBusNamespace = try container.decode(String?.self, forKey: .serviceBusNamespace)
    }
    if container.contains(.sharedAccessPolicyName) {
        self.sharedAccessPolicyName = try container.decode(String?.self, forKey: .sharedAccessPolicyName)
    }
    if container.contains(.sharedAccessPolicyKey) {
        self.sharedAccessPolicyKey = try container.decode(String?.self, forKey: .sharedAccessPolicyKey)
    }
    if container.contains(.topicName) {
        self.topicName = try container.decode(String?.self, forKey: .topicName)
    }
    if container.contains(.propertyColumns) {
        self.propertyColumns = try container.decode([String]?.self, forKey: .propertyColumns)
    }
    if var pageDecoder = decoder as? PageDecoder  {
      if pageDecoder.isPagedData,
        let nextLinkName = pageDecoder.nextLinkName {
          pageDecoder.nextLink = try UnknownCodingKey.decodeStringForKey(decoder: decoder, keyForDecode: nextLinkName)
      }
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    if self.serviceBusNamespace != nil {try container.encode(self.serviceBusNamespace, forKey: .serviceBusNamespace)}
    if self.sharedAccessPolicyName != nil {try container.encode(self.sharedAccessPolicyName, forKey: .sharedAccessPolicyName)}
    if self.sharedAccessPolicyKey != nil {try container.encode(self.sharedAccessPolicyKey, forKey: .sharedAccessPolicyKey)}
    if self.topicName != nil {try container.encode(self.topicName, forKey: .topicName)}
    if self.propertyColumns != nil {try container.encode(self.propertyColumns as! [String]?, forKey: .propertyColumns)}
  }
}

extension DataFactory {
  public static func createServiceBusTopicOutputDataSourcePropertiesProtocol() -> ServiceBusTopicOutputDataSourcePropertiesProtocol {
    return ServiceBusTopicOutputDataSourcePropertiesData()
  }
}
