// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// IotHubSkuDescriptionProtocol is SKU properties.
public protocol IotHubSkuDescriptionProtocol : Codable {
     var resourceType: String? { get set }
     var sku: IotHubSkuInfoProtocol { get set }
     var capacity: IotHubCapacityProtocol { get set }
}
