// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// JobResponseProtocol is the properties of the Job Response object.
public protocol JobResponseProtocol : Codable {
     var jobId: String? { get set }
     var startTimeUtc: Date? { get set }
     var endTimeUtc: Date? { get set }
     var type: JobTypeEnum? { get set }
     var status: JobStatusEnum? { get set }
     var failureReason: String? { get set }
     var statusMessage: String? { get set }
     var parentJobId: String? { get set }
}
