// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// AuthorizationPolicyResourceFormatProtocol is the authorization policy resource format.
public protocol AuthorizationPolicyResourceFormatProtocol : ProxyResourceProtocol {
     var properties: AuthorizationPolicyProtocol? { get set }
}
