// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ConnectorMappingAvailabilityProtocol is connector mapping property availability.
public protocol ConnectorMappingAvailabilityProtocol : Codable {
     var frequency: FrequencyTypesEnum? { get set }
     var interval: Int32 { get set }
}
