// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// HubBillingInfoFormatProtocol is hub billing info.
public protocol HubBillingInfoFormatProtocol : Codable {
     var skuName: String? { get set }
     var minUnits: Int32? { get set }
     var maxUnits: Int32? { get set }
}
