// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// LinkResourceFormatProtocol is the link resource format.
public protocol LinkResourceFormatProtocol : ProxyResourceProtocol {
     var properties: LinkDefinitionProtocol? { get set }
}
