// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// RoleListResultProtocol is the response of list role assignment operation.
public protocol RoleListResultProtocol : Codable {
     var value: [RoleResourceFormatProtocol?]? { get set }
     var _nextLink: String? { get set }
}
