// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// RoleProtocol is the Role definition.
public protocol RoleProtocol : Codable {
     var roleName: String? { get set }
     var description: String? { get set }
}
