// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// RoleAssignmentProtocol is the Role Assignment definition.
public protocol RoleAssignmentProtocol : Codable {
     var tenantId: String? { get set }
     var assignmentName: String? { get set }
     var displayName: [String:String]? { get set }
     var description: [String:String]? { get set }
     var provisioningState: ProvisioningStatesEnum? { get set }
     var role: RoleTypesEnum { get set }
     var principals: [AssignmentPrincipalProtocol] { get set }
     var profiles: ResourceSetDescriptionProtocol? { get set }
     var interactions: ResourceSetDescriptionProtocol? { get set }
     var links: ResourceSetDescriptionProtocol? { get set }
     var kpis: ResourceSetDescriptionProtocol? { get set }
     var sasPolicies: ResourceSetDescriptionProtocol? { get set }
     var connectors: ResourceSetDescriptionProtocol? { get set }
     var views: ResourceSetDescriptionProtocol? { get set }
     var relationshipLinks: ResourceSetDescriptionProtocol? { get set }
     var relationships: ResourceSetDescriptionProtocol? { get set }
     var widgetTypes: ResourceSetDescriptionProtocol? { get set }
     var roleAssignments: ResourceSetDescriptionProtocol? { get set }
     var conflationPolicies: ResourceSetDescriptionProtocol? { get set }
     var segments: ResourceSetDescriptionProtocol? { get set }
}
