// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ZoneListResultProtocol is the response to a Zone List or ListAll operation.
public protocol ZoneListResultProtocol : Codable {
     var value: [ZoneProtocol?]? { get set }
     var _nextLink: String? { get set }
}
