// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// DatabaseAccountCreateUpdateParametersProtocol is parameters to create and update Cosmos DB database accounts.
public protocol DatabaseAccountCreateUpdateParametersProtocol : ResourceProtocol {
     var kind: DatabaseAccountKindEnum? { get set }
     var properties: DatabaseAccountCreateUpdatePropertiesProtocol { get set }
}
