// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// FailoverPolicyProtocol is the failover policy for a given region of a database account.
public protocol FailoverPolicyProtocol : Codable {
     var id: String? { get set }
     var locationName: String? { get set }
     var failoverPriority: Int32? { get set }
}
