// CertificateProvisioningState enumerates the values for certificate provisioning state.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum CertificateProvisioningStateEnum: String, Codable
{
// Deleting specifies the deleting state for certificate provisioning state.
    case Deleting = "Deleting"
// Failed specifies the failed state for certificate provisioning state.
    case Failed = "Failed"
// Succeeded specifies the succeeded state for certificate provisioning state.
    case Succeeded = "Succeeded"
}
