// CustomDomainResourceState enumerates the values for custom domain resource state.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum CustomDomainResourceStateEnum: String, Codable
{
// Active specifies the active state for custom domain resource state.
    case Active = "Active"
// Creating specifies the creating state for custom domain resource state.
    case Creating = "Creating"
// Deleting specifies the deleting state for custom domain resource state.
    case Deleting = "Deleting"
}
