// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
import azureSwiftRuntime
internal struct PasswordProfileData : PasswordProfileProtocol {
    public var additionalProperties: [String:[String: String?]]?
    public var password: String
    public var forceChangePasswordNextLogin: Bool?

        enum CodingKeys: String, CodingKey {case additionalProperties = ""
        case password = "password"
        case forceChangePasswordNextLogin = "forceChangePasswordNextLogin"
        }

  public init(password: String)  {
    self.password = password
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
      if container.contains(.additionalProperties) {
        self.additionalProperties = try container.decode([String:[String: String?]]?.self, forKey: .additionalProperties)
    }
    self.password = try container.decode(String.self, forKey: .password)
    if container.contains(.forceChangePasswordNextLogin) {
        self.forceChangePasswordNextLogin = try container.decode(Bool?.self, forKey: .forceChangePasswordNextLogin)
    }
    if var pageDecoder = decoder as? PageDecoder  {
      if pageDecoder.isPagedData,
        let nextLinkName = pageDecoder.nextLinkName {
          pageDecoder.nextLink = try UnknownCodingKey.decodeStringForKey(decoder: decoder, keyForDecode: nextLinkName)
      }
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    if self.additionalProperties != nil {try container.encode(self.additionalProperties, forKey: .additionalProperties)}
    try container.encode(self.password, forKey: .password)
    if self.forceChangePasswordNextLogin != nil {try container.encode(self.forceChangePasswordNextLogin, forKey: .forceChangePasswordNextLogin)}
  }
}

extension DataFactory {
  public static func createPasswordProfileProtocol(password: String) -> PasswordProfileProtocol {
    return PasswordProfileData(password: password)
  }
}
