// Environment enumerates the values for environment.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum EnvironmentEnum: String, Codable
{
// Linux specifies the linux state for environment.
    case Linux = "Linux"
// Windows specifies the windows state for environment.
    case Windows = "Windows"
}
