// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ResourceRequirementsProtocol is the resource requirements.
public protocol ResourceRequirementsProtocol : Codable {
     var requests: ResourceRequestsProtocol { get set }
     var limits: ResourceLimitsProtocol? { get set }
}
