// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// DocumentDbOutputDataSourcePropertiesProtocol is the properties that are associated with a DocumentDB output.
public protocol DocumentDbOutputDataSourcePropertiesProtocol : Codable {
     var accountId: String? { get set }
     var accountKey: String? { get set }
     var database: String? { get set }
     var collectionNamePattern: String? { get set }
     var partitionKey: String? { get set }
     var documentId: String? { get set }
}
