// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// FunctionRetrieveDefaultDefinitionParametersProtocol is parameters used to specify the type of function to retrieve
// the default definition for.
public protocol FunctionRetrieveDefaultDefinitionParametersProtocol : Codable {
}
