// FirewallState enumerates the values for firewall state.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum FirewallStateEnum: String, Codable
{
// FirewallStateDisabled specifies the firewall state disabled state for firewall state.
    case FirewallStateDisabled = "Disabled"
// FirewallStateEnabled specifies the firewall state enabled state for firewall state.
    case FirewallStateEnabled = "Enabled"
}
