// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// RollingUpgradeRunningStatusProtocol is information about the current running state of the overall upgrade.
public protocol RollingUpgradeRunningStatusProtocol : Codable {
     var code: RollingUpgradeStatusCodeEnum? { get set }
     var startTime: Date? { get set }
     var lastAction: RollingUpgradeActionTypeEnum? { get set }
     var lastActionTime: Date? { get set }
}
