// FileServerType enumerates the values for file server type.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum FileServerTypeEnum: String, Codable
{
// Glusterfs specifies the glusterfs state for file server type.
    case Glusterfs = "glusterfs"
// Nfs specifies the nfs state for file server type.
    case Nfs = "nfs"
}
