// VmPriority enumerates the values for vm priority.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum VmPriorityEnum: String, Codable
{
// Dedicated specifies the dedicated state for vm priority.
    case Dedicated = "dedicated"
// Lowpriority specifies the lowpriority state for vm priority.
    case Lowpriority = "lowpriority"
}
