// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ListQueryKeysResultProtocol is response containing the query API keys for a given Azure Search service.
public protocol ListQueryKeysResultProtocol : Codable {
     var value: [QueryKeyProtocol?]? { get set }
}
