// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// SearchServiceProtocol is describes an Azure Search service and its current state.
public protocol SearchServiceProtocol : ResourceProtocol {
     var properties: SearchServicePropertiesProtocol? { get set }
     var sku: SkuProtocol? { get set }
}
