// AgentRegistrationKeyName enumerates the values for agent registration key name.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum AgentRegistrationKeyNameEnum: String, Codable
{
// Primary specifies the primary state for agent registration key name.
    case Primary = "primary"
// Secondary specifies the secondary state for agent registration key name.
    case Secondary = "secondary"
}
