// OperatingSystemType enumerates the values for operating system type.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum OperatingSystemTypeEnum: String, Codable
{
// Linux specifies the linux state for operating system type.
    case Linux = "Linux"
// Windows specifies the windows state for operating system type.
    case Windows = "Windows"
}
