// ScheduleFrequency enumerates the values for schedule frequency.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum ScheduleFrequencyEnum: String, Codable
{
// Day specifies the day state for schedule frequency.
    case Day = "Day"
// Hour specifies the hour state for schedule frequency.
    case Hour = "Hour"
// Month specifies the month state for schedule frequency.
    case Month = "Month"
// OneTime specifies the one time state for schedule frequency.
    case OneTime = "OneTime"
// Week specifies the week state for schedule frequency.
    case Week = "Week"
}
