// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// GatewayListStatusErrorProtocol is status of gateway is error.
public protocol GatewayListStatusErrorProtocol : Codable {
     var error: GatewayErrorProtocol? { get set }
}
