// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ServerAdministratorsProtocol is an array of administrator user identities.
public protocol ServerAdministratorsProtocol : Codable {
     var members: [String]? { get set }
}
