// AlternateLocationRecoveryOption enumerates the values for alternate location recovery option.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum AlternateLocationRecoveryOptionEnum: String, Codable
{
// CreateVmIfNotFound specifies the create vm if not found state for alternate location recovery option.
    case CreateVmIfNotFound = "CreateVmIfNotFound"
// NoAction specifies the no action state for alternate location recovery option.
    case NoAction = "NoAction"
}
