// InMageV2RpRecoveryPointType enumerates the values for in mage v2 rp recovery point type.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum InMageV2RpRecoveryPointTypeEnum: String, Codable
{
// InMageV2RpRecoveryPointTypeLatest specifies the in mage v2 rp recovery point type latest state for in mage v2 rp
// recovery point type.
    case InMageV2RpRecoveryPointTypeLatest = "Latest"
// InMageV2RpRecoveryPointTypeLatestApplicationConsistent specifies the in mage v2 rp recovery point type latest
// application consistent state for in mage v2 rp recovery point type.
    case InMageV2RpRecoveryPointTypeLatestApplicationConsistent = "LatestApplicationConsistent"
// InMageV2RpRecoveryPointTypeLatestCrashConsistent specifies the in mage v2 rp recovery point type latest crash
// consistent state for in mage v2 rp recovery point type.
    case InMageV2RpRecoveryPointTypeLatestCrashConsistent = "LatestCrashConsistent"
// InMageV2RpRecoveryPointTypeLatestProcessed specifies the in mage v2 rp recovery point type latest processed state
// for in mage v2 rp recovery point type.
    case InMageV2RpRecoveryPointTypeLatestProcessed = "LatestProcessed"
}
