// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ImportExportResponsePropertiesProtocol is response for Import/Export Status operation.
public protocol ImportExportResponsePropertiesProtocol : Codable {
     var requestType: String? { get set }
     var requestId: String? { get set }
     var serverName: String? { get set }
     var databaseName: String? { get set }
     var status: String? { get set }
     var lastModifiedTime: String? { get set }
     var queuedTime: String? { get set }
     var blobUri: String? { get set }
     var errorMessage: String? { get set }
}
