// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// RecommendedElasticPoolProtocol is represents a recommented elastic pool.
public protocol RecommendedElasticPoolProtocol : ProxyResourceProtocol {
     var properties: RecommendedElasticPoolPropertiesProtocol? { get set }
}
