// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ServerDnsAliasListResultProtocol is a list of server DNS aliases.
public protocol ServerDnsAliasListResultProtocol : Codable {
     var value: [ServerDnsAliasProtocol?]? { get set }
     var _nextLink: String? { get set }
}
