// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// SyncGroupPropertiesProtocol is properties of a sync group.
public protocol SyncGroupPropertiesProtocol : Codable {
     var interval: Int32? { get set }
     var lastSyncTime: Date? { get set }
     var conflictResolutionPolicy: SyncConflictResolutionPolicyEnum? { get set }
     var syncDatabaseId: String? { get set }
     var hubDatabaseUserName: String? { get set }
     var hubDatabasePassword: String? { get set }
     var syncState: SyncGroupStateEnum? { get set }
     var schema: SyncGroupSchemaProtocol? { get set }
}
