// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

// NodeReports is the automation Client
import Foundation
import azureSwiftRuntime
extension Commands {
public struct NodeReports {
    public static func Get(resourceGroupName: String, automationAccountName: String, nodeId: String, reportId: String, subscriptionId: String) -> NodeReportsGet {
        return GetCommand(resourceGroupName: resourceGroupName, automationAccountName: automationAccountName, nodeId: nodeId, reportId: reportId, subscriptionId: subscriptionId)
    }
    public static func GetContent(resourceGroupName: String, automationAccountName: String, nodeId: String, reportId: String, subscriptionId: String) -> NodeReportsGetContent {
        return GetContentCommand(resourceGroupName: resourceGroupName, automationAccountName: automationAccountName, nodeId: nodeId, reportId: reportId, subscriptionId: subscriptionId)
    }
    public static func ListByNode(resourceGroupName: String, automationAccountName: String, nodeId: String, subscriptionId: String) -> NodeReportsListByNode {
        return ListByNodeCommand(resourceGroupName: resourceGroupName, automationAccountName: automationAccountName, nodeId: nodeId, subscriptionId: subscriptionId)
    }
}
}
