// AutomaticTuningMode enumerates the values for automatic tuning mode.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum AutomaticTuningModeEnum: String, Codable
{
// Auto specifies the auto state for automatic tuning mode.
    case Auto = "Auto"
// Custom specifies the custom state for automatic tuning mode.
    case Custom = "Custom"
// Inherit specifies the inherit state for automatic tuning mode.
    case Inherit = "Inherit"
// Unspecified specifies the unspecified state for automatic tuning mode.
    case Unspecified = "Unspecified"
}
