// SyncConflictResolutionPolicy enumerates the values for sync conflict resolution policy.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum SyncConflictResolutionPolicyEnum: String, Codable
{
// HubWin specifies the hub win state for sync conflict resolution policy.
    case HubWin = "HubWin"
// MemberWin specifies the member win state for sync conflict resolution policy.
    case MemberWin = "MemberWin"
}
