// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// AzureSkuProtocol is
public protocol AzureSkuProtocol : Codable {
     var name: String { get set }
     var tier: String { get set }
}
