// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// BatchAccountCreateHeadersProtocol is defines headers for Create operation.
public protocol BatchAccountCreateHeadersProtocol : Codable {
     var location: String? { get set }
     var retryAfter: Int32? { get set }
}
