// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// BatchAccountCreateParametersProtocol is parameters supplied to the Create operation.
public protocol BatchAccountCreateParametersProtocol : Codable {
     var location: String { get set }
     var tags: [String:String]? { get set }
     var properties: BatchAccountCreatePropertiesProtocol? { get set }
}
