// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

// ProtectionContainerOperationResults is the open API 2.0 Specs for Azure RecoveryServices Backup service
import Foundation
import azureSwiftRuntime
extension Commands {
public struct ProtectionContainerOperationResults {
    public static func Get(vaultName: String, resourceGroupName: String, subscriptionId: String, fabricName: String, containerName: String, operationId: String) -> ProtectionContainerOperationResultsGet {
        return GetCommand(vaultName: vaultName, resourceGroupName: resourceGroupName, subscriptionId: subscriptionId, fabricName: fabricName, containerName: containerName, operationId: operationId)
    }
}
}
