// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// GenerateUpgradedDefinitionParametersProtocol is the parameters to generate upgraded definition.
public protocol GenerateUpgradedDefinitionParametersProtocol : Codable {
     var targetSchemaVersion: String? { get set }
}
