// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// IntegrationAccountPartnerProtocol is the integration account partner.
public protocol IntegrationAccountPartnerProtocol : ResourceProtocol {
     var properties: IntegrationAccountPartnerPropertiesProtocol { get set }
}
