// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// IntegrationAccountCertificateListResultProtocol is the list of integration account certificates.
public protocol IntegrationAccountCertificateListResultProtocol : Codable {
     var value: [IntegrationAccountCertificateProtocol?]? { get set }
     var _nextLink: String? { get set }
}
