// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// WorkflowTriggerListCallbackUrlQueriesProtocol is gets the workflow trigger callback URL query parameters.
public protocol WorkflowTriggerListCallbackUrlQueriesProtocol : Codable {
     var apiVersion: String? { get set }
     var sp: String? { get set }
     var sv: String? { get set }
     var sig: String? { get set }
}
