// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// X12EnvelopeSettingsProtocol is the X12 agreement envelope settings.
public protocol X12EnvelopeSettingsProtocol : Codable {
     var controlStandardsId: Int32 { get set }
     var useControlStandardsIdAsRepetitionCharacter: Bool { get set }
     var senderApplicationId: String { get set }
     var receiverApplicationId: String { get set }
     var controlVersionNumber: String { get set }
     var interchangeControlNumberLowerBound: Int32 { get set }
     var interchangeControlNumberUpperBound: Int32 { get set }
     var rolloverInterchangeControlNumber: Bool { get set }
     var enableDefaultGroupHeaders: Bool { get set }
     var functionalGroupId: String? { get set }
     var groupControlNumberLowerBound: Int32 { get set }
     var groupControlNumberUpperBound: Int32 { get set }
     var rolloverGroupControlNumber: Bool { get set }
     var groupHeaderAgencyCode: String { get set }
     var groupHeaderVersion: String { get set }
     var transactionSetControlNumberLowerBound: Int32 { get set }
     var transactionSetControlNumberUpperBound: Int32 { get set }
     var rolloverTransactionSetControlNumber: Bool { get set }
     var transactionSetControlNumberPrefix: String? { get set }
     var transactionSetControlNumberSuffix: String? { get set }
     var overwriteExistingTransactionSetControlNumber: Bool { get set }
     var groupHeaderDateFormat: X12DateFormatEnum { get set }
     var groupHeaderTimeFormat: X12TimeFormatEnum { get set }
     var usageIndicator: UsageIndicatorEnum { get set }
}
