// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// X12ProcessingSettingsProtocol is the X12 processing settings.
public protocol X12ProcessingSettingsProtocol : Codable {
     var maskSecurityInfo: Bool { get set }
     var convertImpliedDecimal: Bool { get set }
     var preserveInterchange: Bool { get set }
     var suspendInterchangeOnError: Bool { get set }
     var createEmptyXmlTagsForTrailingSeparators: Bool { get set }
     var useDotAsDecimalSeparator: Bool { get set }
}
