// RoleTypes enumerates the values for role types.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum RoleTypesEnum: String, Codable
{
// Admin specifies the admin state for role types.
    case Admin = "Admin"
// DataAdmin specifies the data admin state for role types.
    case DataAdmin = "DataAdmin"
// DataReader specifies the data reader state for role types.
    case DataReader = "DataReader"
// ManageAdmin specifies the manage admin state for role types.
    case ManageAdmin = "ManageAdmin"
// ManageReader specifies the manage reader state for role types.
    case ManageReader = "ManageReader"
// Reader specifies the reader state for role types.
    case Reader = "Reader"
}
