// SkuTier enumerates the values for sku tier.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum SkuTierEnum: String, Codable
{
// Premium specifies the premium state for sku tier.
    case Premium = "Premium"
// Standard specifies the standard state for sku tier.
    case Standard = "Standard"
}
