// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
import Foundation
// BlobPropertiesProtocol is properties of a blob
public protocol BlobPropertiesProtocol : Codable {
     var lastModified: Date? { get set }
     var etag: String? { get set }
     var contentLength: Int32? { get set }
     var contentType: String? { get set }
     var contentEncoding: String? { get set }
     var contentLanguage: String? { get set }
     var contentMD5: String? { get set }
     var contentDisposition: String? { get set }
     var cacheControl: String? { get set }
     var xMsBlobSequenceNumber: String? { get set }
     var blobType: String? { get set }
     var leaseStatus: LeaseStatusType? { get set }
     var leaseState: LeaseStateType? { get set }
     var leaseDuration: LeaseDurationType? { get set }
     var copyId: String? { get set }
     var copyStatus: CopyStatusType? { get set }
     var copySource: String? { get set }
     var copyProgress: String? { get set }
     var copyCompletionTime: Date? { get set }
     var copyStatusDescription: String? { get set }
     var serverEncrypted: Bool? { get set }
     var incrementalCopy: Bool? { get set }
}
