// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
import Foundation
// BlobsDeleteHeadersProtocol is defines headers for Delete operation.
public protocol BlobsDeleteHeadersProtocol : Codable {
     var requestId: String? { get set }
     var version: String? { get set }
     var date: Date? { get set }
}
