// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
import Foundation
// ContainerGetPropertiesHeadersProtocol is defines headers for GetProperties operation.
public protocol ContainerGetPropertiesHeadersProtocol : Codable {
     var metadata: [String:String]? { get set }
     var eTag: String? { get set }
     var lastModified: String? { get set }
     var leaseDuration: LeaseDurationType? { get set }
     var leaseState: LeaseStateType? { get set }
     var leaseStatus: LeaseStatusType? { get set }
     var requestId: String? { get set }
     var version: String? { get set }
     var date: Date? { get set }
     var blobPublicAccess: PublicAccessType? { get set }
}
