// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
import azureSwiftRuntime
internal struct ReplicationPropertiesData : ReplicationPropertiesProtocol {
    public var provisioningState: ProvisioningStateEnum?
    public var status: StatusProtocol?

        enum CodingKeys: String, CodingKey {case provisioningState = "provisioningState"
        case status = "status"
        }

  public init()  {
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
      if container.contains(.provisioningState) {
        self.provisioningState = try container.decode(ProvisioningStateEnum?.self, forKey: .provisioningState)
    }
    if container.contains(.status) {
        self.status = try container.decode(StatusData?.self, forKey: .status)
    }
    if var pageDecoder = decoder as? PageDecoder  {
      if pageDecoder.isPagedData,
        let nextLinkName = pageDecoder.nextLinkName {
          pageDecoder.nextLink = try UnknownCodingKey.decodeStringForKey(decoder: decoder, keyForDecode: nextLinkName)
      }
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    if self.provisioningState != nil {try container.encode(self.provisioningState, forKey: .provisioningState)}
    if self.status != nil {try container.encode(self.status as! StatusData?, forKey: .status)}
  }
}

extension DataFactory {
  public static func createReplicationPropertiesProtocol() -> ReplicationPropertiesProtocol {
    return ReplicationPropertiesData()
  }
}
