// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// CustomDomainPropertiesParametersProtocol is the JSON object that contains the properties of the custom domain to
// create.
public protocol CustomDomainPropertiesParametersProtocol : Codable {
     var hostName: String { get set }
}
