// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ValidateCustomDomainInputProtocol is input of the custom domain to be validated for DNS mapping.
public protocol ValidateCustomDomainInputProtocol : Codable {
     var hostName: String { get set }
}
