// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ServiceUpdatePropertiesProtocol is the service resource properties for patch operations.
public protocol ServiceUpdatePropertiesProtocol : ServicePropertiesBaseProtocol {
}
