// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// StatelessServiceUpdatePropertiesProtocol is the properties of a stateless service resource for patch operations.
public protocol StatelessServiceUpdatePropertiesProtocol : ServiceUpdatePropertiesProtocol {
     var instanceCount: Int32? { get set }
}
