// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// AzureBackupServerEngineProtocol is backup engine type when Azure Backup Server is used to manage the backups.
public protocol AzureBackupServerEngineProtocol : BackupEngineBaseProtocol {
}
