// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// GenericContainerExtendedInfoProtocol is container extended information
public protocol GenericContainerExtendedInfoProtocol : Codable {
     var rawCertData: String? { get set }
     var containerIdentityInfo: ContainerIdentityInfoProtocol? { get set }
     var serviceEndpoints: [String:String]? { get set }
}
