// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ILRRequestResourceProtocol is parameters to restore file/folders API.
public protocol ILRRequestResourceProtocol : ResourceProtocol {
     var properties: ILRRequestProtocol? { get set }
}
