// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// JobQueryObjectProtocol is filters to list the jobs.
public protocol JobQueryObjectProtocol : Codable {
     var status: JobStatusEnum? { get set }
     var backupManagementType: BackupManagementTypeEnum? { get set }
     var operation: JobOperationTypeEnum? { get set }
     var jobId: String? { get set }
     var startTime: Date? { get set }
     var endTime: Date? { get set }
}
