// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ProtectedItemResourceListProtocol is list of ProtectedItem resources
public protocol ProtectedItemResourceListProtocol : ResourceListProtocol {
     var value: [ProtectedItemResourceProtocol?]? { get set }
}
