// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// SubProtectionPolicyProtocol is sub-protection policy which includes schedule and retention
public protocol SubProtectionPolicyProtocol : Codable {
     var policyType: String? { get set }
     var schedulePolicy: SchedulePolicyProtocol? { get set }
     var retentionPolicy: RetentionPolicyProtocol? { get set }
}
