// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// AzureStorageCredentialsInfoProtocol is credentials to access Azure File Share.
public protocol AzureStorageCredentialsInfoProtocol : Codable {
     var accountKey: String? { get set }
     var accountKeySecretReference: KeyVaultSecretReferenceProtocol? { get set }
}
