// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// VirtualMachineConfigurationProtocol is settings for OS image.
public protocol VirtualMachineConfigurationProtocol : Codable {
     var imageReference: ImageReferenceProtocol? { get set }
}
