// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ComputeNodeProtocol is
public protocol ComputeNodeProtocol : Codable {
     var id: String? { get set }
     var url: String? { get set }
     var state: ComputeNodeStateEnum? { get set }
     var schedulingState: SchedulingStateEnum? { get set }
     var stateTransitionTime: Date? { get set }
     var lastBootTime: Date? { get set }
     var allocationTime: Date? { get set }
     var ipAddress: String? { get set }
     var affinityId: String? { get set }
     var vmSize: String? { get set }
     var totalTasksRun: Int32? { get set }
     var runningTasksCount: Int32? { get set }
     var totalTasksSucceeded: Int32? { get set }
     var recentTasks: [TaskInformationProtocol?]? { get set }
     var startTask: StartTaskProtocol? { get set }
     var startTaskInfo: StartTaskInformationProtocol? { get set }
     var certificateReferences: [CertificateReferenceProtocol?]? { get set }
     var errors: [ComputeNodeErrorProtocol?]? { get set }
     var isDedicated: Bool? { get set }
     var endpointConfiguration: ComputeNodeEndpointConfigurationProtocol? { get set }
}
