// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// JobDeleteHeadersProtocol is defines headers for Delete operation.
public protocol JobDeleteHeadersProtocol : Codable {
     var clientRequestId: String? { get set }
     var requestId: String? { get set }
}
