// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// TaskInformationProtocol is
public protocol TaskInformationProtocol : Codable {
     var taskUrl: String? { get set }
     var jobId: String? { get set }
     var taskId: String? { get set }
     var subtaskId: Int32? { get set }
     var taskState: TaskStateEnum { get set }
     var executionInfo: TaskExecutionInformationProtocol? { get set }
}
