// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// UserIdentityProtocol is specify either the userName or autoUser property, but not both.
public protocol UserIdentityProtocol : Codable {
     var userName: String? { get set }
     var autoUser: AutoUserSpecificationProtocol? { get set }
}
