// ConditionOperator enumerates the values for condition operator.

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
public enum ConditionOperatorEnum: String, Codable
{
// ConditionOperatorGreaterThan specifies the condition operator greater than state for condition operator.
    case ConditionOperatorGreaterThan = "GreaterThan"
// ConditionOperatorGreaterThanOrEqual specifies the condition operator greater than or equal state for condition
// operator.
    case ConditionOperatorGreaterThanOrEqual = "GreaterThanOrEqual"
// ConditionOperatorLessThan specifies the condition operator less than state for condition operator.
    case ConditionOperatorLessThan = "LessThan"
// ConditionOperatorLessThanOrEqual specifies the condition operator less than or equal state for condition operator.
    case ConditionOperatorLessThanOrEqual = "LessThanOrEqual"
}
