// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
import azureSwiftRuntime
internal struct RuleMetricDataSourceData : RuleMetricDataSourceProtocol, RuleDataSourceProtocol {
    public var resourceUri: String?
    public var metricName: String?

        enum CodingKeys: String, CodingKey {case resourceUri = "resourceUri"
        case metricName = "metricName"
        }

  public init()  {
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
      if container.contains(.resourceUri) {
        self.resourceUri = try container.decode(String?.self, forKey: .resourceUri)
    }
    if container.contains(.metricName) {
        self.metricName = try container.decode(String?.self, forKey: .metricName)
    }
    if var pageDecoder = decoder as? PageDecoder  {
      if pageDecoder.isPagedData,
        let nextLinkName = pageDecoder.nextLinkName {
          pageDecoder.nextLink = try UnknownCodingKey.decodeStringForKey(decoder: decoder, keyForDecode: nextLinkName)
      }
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    if self.resourceUri != nil {try container.encode(self.resourceUri, forKey: .resourceUri)}
    if self.metricName != nil {try container.encode(self.metricName, forKey: .metricName)}
  }
}

extension DataFactory {
  public static func createRuleMetricDataSourceProtocol() -> RuleMetricDataSourceProtocol {
    return RuleMetricDataSourceData()
  }
}
