// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ApplicationLogsConfigProtocol is application logs configuration.
public protocol ApplicationLogsConfigProtocol : Codable {
     var fileSystem: FileSystemApplicationLogsConfigProtocol? { get set }
     var azureTableStorage: AzureTableStorageApplicationLogsConfigProtocol? { get set }
     var azureBlobStorage: AzureBlobStorageApplicationLogsConfigProtocol? { get set }
}
