// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// AutoHealTriggersProtocol is triggers for auto-heal.
public protocol AutoHealTriggersProtocol : Codable {
     var requests: RequestsBasedTriggerProtocol? { get set }
     var privateBytesInKB: Int32? { get set }
     var statusCodes: [StatusCodesBasedTriggerProtocol?]? { get set }
     var slowRequests: SlowRequestsBasedTriggerProtocol? { get set }
}
