// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// BackupItemPropertiesProtocol is backupItem resource specific properties
public protocol BackupItemPropertiesProtocol : Codable {
     var backupId: Int32? { get set }
     var storageAccountUrl: String? { get set }
     var blobName: String? { get set }
     var name: String? { get set }
     var status: BackupItemStatusEnum? { get set }
     var sizeInBytes: Int64? { get set }
     var created: Date? { get set }
     var log: String? { get set }
     var databases: [DatabaseBackupSettingProtocol?]? { get set }
     var scheduled: Bool? { get set }
     var lastRestoreTimeStamp: Date? { get set }
     var finishedTimeStamp: Date? { get set }
     var correlationId: String? { get set }
     var websiteSizeInBytes: Int64? { get set }
}
