// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// DeletedWebAppCollectionProtocol is collection of deleted apps.
public protocol DeletedWebAppCollectionProtocol : Codable {
     var value: [DeletedSiteProtocol] { get set }
     var _nextLink: String? { get set }
}
