// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// DiagnosticCategoryProtocol is class representing detector definition
public protocol DiagnosticCategoryProtocol : ProxyOnlyResourceProtocol {
     var properties: DiagnosticCategoryPropertiesProtocol? { get set }
}
