// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ErrorEntityProtocol is body of the error response returned from the API.
public protocol ErrorEntityProtocol : Codable {
     var extendedCode: String? { get set }
     var messageTemplate: String? { get set }
     var parameters: [String]? { get set }
     var innerErrors: [ErrorEntityProtocol?]? { get set }
     var code: String? { get set }
     var message: String? { get set }
}
