// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// FunctionSecretsPropertiesProtocol is functionSecrets resource specific properties
public protocol FunctionSecretsPropertiesProtocol : Codable {
     var key: String? { get set }
     var triggerUrl: String? { get set }
}
