// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// IpSecurityRestrictionProtocol is IP security restriction on an app.
public protocol IpSecurityRestrictionProtocol : Codable {
     var ipAddress: String { get set }
     var subnetMask: String? { get set }
}
