// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// MetricDefinitionProtocol is metadata for a metric.
public protocol MetricDefinitionProtocol : ProxyOnlyResourceProtocol {
     var properties: MetricDefinitionPropertiesProtocol? { get set }
}
