// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// MetricDefinitionPropertiesProtocol is metricDefinition resource specific properties
public protocol MetricDefinitionPropertiesProtocol : Codable {
     var name: String? { get set }
     var unit: String? { get set }
     var primaryAggregationType: String? { get set }
     var metricAvailabilities: [MetricAvailabililyProtocol?]? { get set }
     var displayName: String? { get set }
}
