// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// NetworkFeaturesProtocol is full view of network features for an app (presently VNET integration and Hybrid
// Connections).
public protocol NetworkFeaturesProtocol : ProxyOnlyResourceProtocol {
     var properties: NetworkFeaturesPropertiesProtocol? { get set }
}
