// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// RecommendationPropertiesProtocol is recommendation resource specific properties
public protocol RecommendationPropertiesProtocol : Codable {
     var creationTime: Date? { get set }
     var recommendationId: String? { get set }
     var resourceId: String? { get set }
     var resourceScope: ResourceScopeTypeEnum? { get set }
     var ruleName: String? { get set }
     var displayName: String? { get set }
     var message: String? { get set }
     var level: NotificationLevelEnum? { get set }
     var channels: ChannelsEnum? { get set }
     var tags: [String]? { get set }
     var actionName: String? { get set }
     var startTime: Date? { get set }
     var endTime: Date? { get set }
     var nextNotificationTime: Date? { get set }
     var notificationExpirationTime: Date? { get set }
     var notifiedTime: Date? { get set }
     var score: Double? { get set }
     var isDynamic: Bool? { get set }
     var extensionName: String? { get set }
     var bladeName: String? { get set }
     var forwardLink: String? { get set }
}
