// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// SnapshotCollectionProtocol is collection of snapshots which can be used to revert an app to a previous time.
public protocol SnapshotCollectionProtocol : Codable {
     var value: [SnapshotProtocol] { get set }
     var _nextLink: String? { get set }
}
