// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// TriggeredJobRunPropertiesProtocol is triggeredJobRun resource specific properties
public protocol TriggeredJobRunPropertiesProtocol : Codable {
     var id: String? { get set }
     var name: String? { get set }
     var status: TriggeredWebJobStatusEnum? { get set }
     var startTime: Date? { get set }
     var endTime: Date? { get set }
     var duration: String? { get set }
     var outputUrl: String? { get set }
     var errorUrl: String? { get set }
     var url: String? { get set }
     var jobName: String? { get set }
     var trigger: String? { get set }
}
