// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// VirtualApplicationProtocol is virtual application in an app.
public protocol VirtualApplicationProtocol : Codable {
     var virtualPath: String? { get set }
     var physicalPath: String? { get set }
     var preloadEnabled: Bool? { get set }
     var virtualDirectories: [VirtualDirectoryProtocol?]? { get set }
}
