// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// CreateProtectionContainerMappingInputPropertiesProtocol is configure pairing input properties.
public protocol CreateProtectionContainerMappingInputPropertiesProtocol : Codable {
     var targetProtectionContainerId: String? { get set }
     var policyId: String? { get set }
     var providerSpecificInput: ReplicationProviderSpecificContainerMappingInputProtocol? { get set }
}
