// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// DisableProtectionProviderSpecificInputProtocol is disable protection provider specific input.
public protocol DisableProtectionProviderSpecificInputProtocol : Codable {
}
