// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// EnableProtectionInputProtocol is enable protection input.
public protocol EnableProtectionInputProtocol : Codable {
     var properties: EnableProtectionInputPropertiesProtocol? { get set }
}
