// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ExportJobDetailsProtocol is this class represents details for export jobs workflow.
public protocol ExportJobDetailsProtocol : JobDetailsProtocol {
     var blobUri: String? { get set }
     var sasToken: String? { get set }
}
