// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ProtectionContainerProtocol is protection container details.
public protocol ProtectionContainerProtocol : ResourceProtocol {
     var properties: ProtectionContainerPropertiesProtocol? { get set }
}
