// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// RecoveryPlanProtocol is recovery plan details.
public protocol RecoveryPlanProtocol : ResourceProtocol {
     var properties: RecoveryPlanPropertiesProtocol? { get set }
}
