// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// ResumeJobParamsPropertiesProtocol is resume job properties.
public protocol ResumeJobParamsPropertiesProtocol : Codable {
     var comments: String? { get set }
}
