// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// RunAsAccountProtocol is CS Accounts Details.
public protocol RunAsAccountProtocol : Codable {
     var accountId: String? { get set }
     var accountName: String? { get set }
}
