// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// SwitchProtectionJobDetailsProtocol is this class represents details for switch protection job.
public protocol SwitchProtectionJobDetailsProtocol : JobDetailsProtocol {
     var newReplicationProtectedItemId: String? { get set }
}
