// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// VCenterCollectionProtocol is collection of vCenter details.
public protocol VCenterCollectionProtocol : Codable {
     var value: [VCenterProtocol?]? { get set }
     var _nextLink: String? { get set }
}
