// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// VersionDetailsProtocol is version related deatils.
public protocol VersionDetailsProtocol : Codable {
     var version: String? { get set }
     var expiryDate: Date? { get set }
     var status: AgentVersionStatusEnum? { get set }
}
