// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
import Foundation
// VMwareDetailsProtocol is store the fabric details specific to the VMware fabric.
public protocol VMwareDetailsProtocol : FabricSpecificDetailsProtocol {
     var processServers: [ProcessServerProtocol?]? { get set }
     var masterTargetServers: [MasterTargetServerProtocol?]? { get set }
     var runAsAccounts: [RunAsAccountProtocol?]? { get set }
     var replicationPairCount: String? { get set }
     var processServerCount: String? { get set }
     var agentCount: String? { get set }
     var protectedServers: String? { get set }
     var systemLoad: String? { get set }
     var systemLoadStatus: String? { get set }
     var cpuLoad: String? { get set }
     var cpuLoadStatus: String? { get set }
     var totalMemoryInBytes: Int64? { get set }
     var availableMemoryInBytes: Int64? { get set }
     var memoryUsageStatus: String? { get set }
     var totalSpaceInBytes: Int64? { get set }
     var availableSpaceInBytes: Int64? { get set }
     var spaceUsageStatus: String? { get set }
     var webLoad: String? { get set }
     var webLoadStatus: String? { get set }
     var databaseServerLoad: String? { get set }
     var databaseServerLoadStatus: String? { get set }
     var csServiceStatus: String? { get set }
     var ipAddress: String? { get set }
     var agentVersion: String? { get set }
     var hostName: String? { get set }
     var lastHeartbeat: Date? { get set }
     var versionStatus: String? { get set }
     var sslCertExpiryDate: Date? { get set }
     var sslCertExpiryRemainingDays: Int32? { get set }
     var psTemplateVersion: String? { get set }
     var agentExpiryDate: Date? { get set }
     var agentVersionDetails: VersionDetailsProtocol? { get set }
}
